/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.103
 * Generated at: 2020-04-08 13:36:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t");

		String userID = null;
		if (session.getAttribute("userID") != null) {
			userID = (String) session.getAttribute("userID");
		}
		String toID = null;
		if (request.getParameter("toID") != null) {
			toID = (String) request.getParameter("toID");
		}
		if (userID == null) {
			session.setAttribute("messageType", "오류메시지");
			session.setAttribute("messageContent", "현재 로그인이 되어있지 않습니다.");
			response.sendRedirect("index.jsp");
			return;
		}
		if (toID == null) {
			session.setAttribute("messageType", "오류메시지");
			session.setAttribute("messageContent", "대화 상대가 지정되지 않았습니다.");
			response.sendRedirect("index.jsp");
			return;
		}
	
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\t<title>JSP Ajax 실시간 회원제 채팅 서비스</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction autoClosingAlert(selector, delay) {\r\n");
      out.write("\t\t\tvar alert = $(selector).alert();\r\n");
      out.write("\t\t\talert.show();\r\n");
      out.write("\t\t\twindow.setTimeout(function() { alert.hide() }, delay);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction submitFunction() {\r\n");
      out.write("\t\t\tvar fromID = '");
      out.print( userID );
      out.write("';\r\n");
      out.write("\t\t\tvar toID = '");
      out.print( toID );
      out.write("';\r\n");
      out.write("\t\t\tvar chatContent = $('#chatContent').val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"./chatSubmitServlet\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tfromID: encodeURIComponent(fromID),\r\n");
      out.write("\t\t\t\t\ttoID: encodeURIComponent(toID),\r\n");
      out.write("\t\t\t\t\tchatContent: encodeURIComponent(chatContent),\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\tif(result == 1) {\r\n");
      out.write("\t\t\t\t\t\tautoClosingAlert('#successMessage', 2000);\r\n");
      out.write("\t\t\t\t\t} else if (result == 0) {\r\n");
      out.write("\t\t\t\t\t\tautoClosingAlert('#dangerMessage', 2000);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tautoClosingAlert('#warningMessage', 2000);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#chatContent').val();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar lastID = 0;\r\n");
      out.write("\t\tfunction chatListFunction(type) {\r\n");
      out.write("\t\t\tvar fromID = '");
      out.print( userID );
      out.write("';\r\n");
      out.write("\t\t\tvar toID = '");
      out.print( toID );
      out.write("';\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"./chatListServlet\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tfromID: encodeURIComponent(fromID),\r\n");
      out.write("\t\t\t\t\ttoID: encodeURIComponent(toID),\r\n");
      out.write("\t\t\t\t\tlistType: type\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data == \"\") return;\r\n");
      out.write("\t\t\t\t\tvar parsed = JSON.parse(data);\r\n");
      out.write("\t\t\t\t\tvar result = parsed.result;\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < result.length; i++) {\r\n");
      out.write("\t\t\t\t\t\taddChat(result[i][0].value, result[i][2].value, result[i][3].value)\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tlastID = Number(parsed.last);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction addChat(chatName, chatContent, chatTime) {\r\n");
      out.write("\t\t\t$('chatList').append('<div class=\"row\">' +\r\n");
      out.write("\t\t\t\t\t'<div class=\"col-lg-12\">' +\r\n");
      out.write("\t\t\t\t\t'<div class=\"media\">' +\r\n");
      out.write("\t\t\t\t\t'<a class=\"pull-left\" href=\"#\">' +\r\n");
      out.write("\t\t\t\t\t'<img class=\"media-object img-circle\" style=\"width: 30px; height: 30px; src=\"images/icon.png\" alt=\"\">' +\r\n");
      out.write("\t\t\t\t\t'</a>' +\r\n");
      out.write("\t\t\t\t\t'<div class=\"media-body\">' +\r\n");
      out.write("\t\t\t\t\t'<h4 class=\"media-heading\">' +\r\n");
      out.write("\t\t\t\t\tchatName +\r\n");
      out.write("\t\t\t\t\t'<span class=\"small pull-right\">' +\r\n");
      out.write("\t\t\t\t\tchatTime +\r\n");
      out.write("\t\t\t\t\t'</span>' +\r\n");
      out.write("\t\t\t\t\t'</h4>' +\r\n");
      out.write("\t\t\t\t\t'<p>' +\r\n");
      out.write("\t\t\t\t\tchatContent +\r\n");
      out.write("\t\t\t\t\t'</p>' +\r\n");
      out.write("\t\t\t\t\t'</div>' +\r\n");
      out.write("\t\t\t\t\t'</div>' +\r\n");
      out.write("\t\t\t\t\t'</div>' +\r\n");
      out.write("\t\t\t\t\t'</div>' +\r\n");
      out.write("\t\t\t\t\t'<hr>');\r\n");
      out.write("\t\t\t$('#chatList').scrollTop($('#chatList')[0].scrollHeight);\r\n");
      out.write(" \t\t}\r\n");
      out.write("\t\tfunction getInfiniteChat() {\r\n");
      out.write("\t\t\tsetInterval(function() {\r\n");
      out.write("\t\t\t\tchatListFunction(lastID);\r\n");
      out.write("\t\t\t}, 3000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"collapse\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">실시간 회원제 채팅 서비스</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">메인</a>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				if(userID != null) {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">회원관리<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"container bootstrap snippet\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portlet portlet-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portlet-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portlet-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4><i calss=\"fa fa-circle text-green\"></i>실시간 채팅창</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"chat\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"chatList\" class=\"portlet-body chat-widget\" style=\"overflow-y: auto; width:auto; height: 600px;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"portlet-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" style=\"height: 90px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea style=\"height: 80px;\" id=\"chatContent\" class=\"form-control\" placeholder=\"메시지를 입력하세요.\"  maxlength=\"100\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default pull-right\" onclick=\"submitFunction();\">전송</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alert alert-success\" id=\"successMessage\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<strong>메시지 전송에 성공했습니다.</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alert alert-danger\" id=\"dangerMessage\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<strong>이름과 내용을 모두 입력해주세요.</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"alert alert-warning\" id=\"warningMessage\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<strong>데이터 베이스 오류가 발생했습니다.</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t");

			String messageContent = null;
			if(session.getAttribute("messageContent") != null) {
				messageContent = (String) session.getAttribute("messageContent");
			}
			String messageType = null;
			if(session.getAttribute("messageType") != null) {
				messageType = (String) session.getAttribute("messageType");
			}
			if(messageContent != null) {
		
      out.write("\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"messageModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"vertical-alignment-helper\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog vertical-align-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content ");
 if(messageType.equals("오류 메시지")) out.println("panel-warning"); else out.println("panel-success"); 
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Close</span>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( messageType );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( messageContent );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"checkModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"vertical-alignment-helper\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog vertical-align-center\">\r\n");
      out.write("\t\t\t\t\t<div id=\"checkType\" class=\"modal-content pannel-info\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Close</span>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t확인 메시지\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"checkMessage\" class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$('#messageModal').modal(\"show\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");
 
			session.removeAttribute("messageContent");
			session.removeAttribute("messageType");
			}
		
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\tchatListFunction('ten');\r\n");
      out.write("\t\t\t\tgetInfiniteChat();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
